# Build Docker image for this app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker?view=vsts
pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName:    'onsched_fullstack_node_ex'
  imageLatest:  '$(imageName):latest'
  imageRelease: '$(imageName):$(Build.BuildId)'
  # define two more variables dockerId and dockerPassword in the build pipeline in UI

steps:
- script: |
    yarn install
    yarn test:ci
    docker build -f Dockerfile -e NODE_ENV=production --tag $(dockerId).azurecr.io/$(imageRelease) --tag $(dockerId).azurecr.io/$(imageLatest) .
    docker login -u $(dockerId) -p $pswd $(dockerId).azurecr.io
    docker push $(dockerId).azurecr.io/$(imageRelease)
    docker push $(dockerId).azurecr.io/$(imageLatest)
  env:
    pswd: $(dockerPassword)

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/TEST_RESULTS.xml'
    testRunTitle:     'Test results for JavaScript'

- task: PublishCodeCoverageResults@1
  inputs: 
    codeCoverageTool:    Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
    reportDirectory:     '$(System.DefaultWorkingDirectory)/**/coverage'

