# Docker Compose setup for working in development
version: '3'
services:
  web:
    build: .
    image: onsched_fs_node_ex:latest
    # make sure development code changes are 
    # picked up by the container with the 
    # command and volumes options 
    command: yarn run dev
    volumes:
      - .:/usr/app
    environment:
      # environment variables here are only
      # available during runtime execution
      # not during the image build process
      # PORT: 5000
      NODE_ENV: development
    ports:
      - "5000:5000"
      - "3000:3000"

